engine: ~2
name: covidfaq

healthcheck:
  liveness:
    initialDelaySeconds: 180
  readiness:
    initialDelaySeconds: 180

public:
  ingress: true

environments:
  dev-ca2:
    environment:
      BUCKET_NAME: dialoguecorp.covidfaq.dev.ca-central-1
  prod-ca:
    environment:
      BUCKET_NAME: dialoguecorp.covidfaq.prod.ca-central-1

scale:
  vertical: large.mem4x
  horizontal: 2
  cpuNoLimits: true
  memThreshold: false
  qos: guaranteed
tolerations:
  "dialoguecorp.com/covidbot": "Exists"
nodeSelector:
  "dialoguecorp.com/covidbot": "true"

addons:
  iamRole: true
