engine: 0.0.0-pr111+20e6a3a
name: covidfaq

healthcheck:
  liveness:
    initialDelaySeconds: 20
  readiness:
    initialDelaySeconds: 15


public:
  ingress: true

addons:
  monitoring: true

environments:
  dev-ca2:
    environment:
      elastic_search_host: es-covidfaq.dev.dialoguecorp.com
  prod-ca:
    environment:
      elastic_search_host: es-covidfaq.dialoguecorp.com

scale:
  vertical: large
  horizontal: 2-4
tolerations:
  "dialoguecorp.com/covidbot": "Exists"
nodeSelector:
  "dialoguecorp.com/covidbot": "true"
