engine: ~2
name: covidfaq

healthcheck:
  liveness:
    initialDelaySeconds: 180
  readiness:
    initialDelaySeconds: 180

public:
  ingress: true

scale:
  vertical: x-large.mem
  horizontal: 2-4
  memThreshold: false
tolerations:
  "dialoguecorp.com/covidbot": "Exists"
nodeSelector:
  "dialoguecorp.com/covidbot": "true"

dependencies:
  elasticsearch:
    version: 7.6.1
    repo: "@elastic"
    settings:
      clusterName: faq
      replicas: 2
      minimumMasterNodes: 1

      nodeSelector:
        "dialoguecorp.com/covidbot": "true"
      tolerations:
        - key: "dialoguecorp.com/covidbot"
          operator: "Exists"

addons:
  iamRole: true
