ingress:
  enabled: true

app:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

rasa:
  versions:
    rasaProduction:
      resources:
        requests:
          memory: 2048Mi
          cpu: 2000m
        limits:
          memory: 2048Mi
          cpu: 2000m
    rasaWorker:
      resources:
        requests:
          memory: 4096Mi
          cpu: 2000m
        limits:
          memory: 4096Mi
          cpu: 2000m
  additionalChannelCredentials:
    rest:
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

rasax:
  resources:
    requests:
      memory: 1024Mi
      cpu: 1000m
    limits:
      memory: 1024Mi
      cpu: 1000m
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

nginx:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

duckling:
  requests:
    memory: 256Mi
    cpu: 500m
  limits:
    memory: 256Mi
    cpu: 500m
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

eventService:
  requests:
    memory: 1024Mi
    cpu: 1000m
  limits:
    memory: 1024Mi
    cpu: 1000m
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

rabbitmq:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m
  nodeSelector:
    "dialoguecorp.com/covidbot": "true"
  tolerations:
    - key: "dialoguecorp.com/covidbot"
      operator: "Exists"

redis:
  master:
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 256Mi
        cpu: 200m
    nodeSelector:
      "dialoguecorp.com/covidbot": "true"
    tolerations:
      - key: "dialoguecorp.com/covidbot"
        operator: "Exists"

postgresql:
  resources:
    requests:
      memory: 256Mi
      cpu: 1000m
    limits:
      memory: 256Mi
      cpu: 1000m
  master:
    nodeSelector:
      "dialoguecorp.com/covidbot": "true"
    tolerations:
      - key: "dialoguecorp.com/covidbot"
        operator: "Exists"
