clusterName: covidfaq
replicas: 2
minimumMasterNodes: 1

nodeSelector:
  "dialoguecorp.com/covidbot": "true"
tolerations:
  - key: "dialoguecorp.com/covidbot"
    operator: "Exists"

ingress:
  enabled: true
