# train_file: 'covidfaq/data/covidfaq_data/covidfaq_data/crowdsource/20200416_quebec_faq_en_cleaned_collection1_2_3_newformat/train_overlapping.json'
# dev_files:
  # dev_file_1: 'covidfaq/data/covidfaq_data/crowdsource/20200416_quebec_faq_en_cleaned_collection1_2_3_newformat/val_overlapping.json'
# test_file: 'covidfaq/data/covidfaq_data/crowdsource/20200416_quebec_faq_en_cleaned_collection1_2_3_newformat/test.json'
# keep_ood: false

ckpt_to_resume: covidfaq/bert_en_model/output/bert_model.ckpt 

outlier:
    ood_filename: 'covidfaq/bert_en_model/en_ood_model.pkl'
    model_name: 'local_outlier_factor'
    training_data_files:
        - covidfaq/data/covidfaq_data/crowdsource/20200416_quebec_faq_en_cleaned_collection1_2_3/train.json
        - covidfaq/data/covidfaq_data/crowdsource/20200416_quebec_faq_en_cleaned_collection1_2_3/validation.json
        - covidfaq/data/covidfaq_data/crowdsource/20200522_quebec_faq_en_cleaned_collection4/test.json

accumulate_grad_batches: 1
batch_size: 64
gradient_clipping: 0

logging:
  logger: 'tensorboard'

loss_type: classification
max_epochs: 9999
max_paragraph_len: 100
max_question_len: 100
model:
  bert_base: bert-base-uncased
  dropout: 0.1
  dropout_bert: 0.1
  freeze_bert: false
  layers_post_pooling: []
  layers_pre_pooling: []
  name: bert_encoder
  normalize_model_result: false
  pooling_type: avg
  single_encoder: true
optimizer:
  lr: 1.417e-05
  name: adamw
patience: 35
precision: 32
seed: null
tokenizer_name: bert-base-uncased
